wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    framework: huggingface
    huggingface_version: 4.42.3
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1727454747.203305
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 41
      - 49
      - 53
      - 54
      - 55
      - 63
      - 74
      - 79
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 41
      - 49
      - 53
      - 54
      - 55
      - 63
      - 74
      - 79
      3:
      - 2
      - 13
      - 19
      - 23
      4: 3.9.13
      5: 0.13.3
      6: 4.42.3
      8:
      - 1
      - 3
      - 5
epochs:
  desc: null
  value: 5
learning_rate:
  desc: null
  value: 0.0025
metric_index:
  desc: null
  value: 1
save_model_path:
  desc: null
  value: C:\Users\coach\myfiles\postdoc\Fire\models\Unet_convnextT_27092024.pth
