name: Daily Python Script

on:
  push:
  schedule:
    - cron: "0 22 * * *" # Runs at 22:00 UTC (00:00 SAST)

permissions:
  contents: read

jobs:
  test:

    # runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - uses: actions/cache@v3
      id: cache
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.*') }}
        restore-keys: | 
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip uv
        uv pip install -r requirements.txt --system
      if: steps.cache.outputs.cache-hit != 'true' # Skip if cache is valid
    - name: Decode secrets file and setup service account key
      run: |
        echo ${{ secrets.EE_SERVICE_ACCOUNT_KEY }} | base64 -d > secret.json
    - name: Debug Python Path
      run: python -c "import sys; print(sys.path)"
    - name: Run Python script
      run: PYTHONPATH=src python src/components/stage1_daily.py
